source :rubygems
source "http://rubygems.org"

gem "hoe"
gem "opengl"
gem "gosu"
gem "texplay"
gem "rake-compiler"
gem "rdoc"
gem "devil", :platforms => [:ruby, :mingw]
gem "chunky_png"
gem "chipmunk"
gem "statemachine"


gem "mocha"
gem "rspec-expectations"
gem "cucumber"
