input_config:
  keyboard_config:
    Gosu::KbLeft: KeyActions::LEFT
    Gosu::KbRight: KeyActions::RIGHT
    Gosu::KbUp: KeyActions::UP
    Gosu::KbDown: KeyActions::DOWN
    Gosu::KbSpace: KeyActions::FIRE
    Gosu::KbEnter: KeyActions::MENU_ENTER
    Gosu::KbReturn: KeyActions::MENU_ENTER
    Gosu::KbM: KeyActions::MENU
    Gosu::KbQ: KeyActions::QUIT
  gamepad_config:
    Gosu::GpLeft: KeyActions::LEFT
    Gosu::GpRight: KeyActions::RIGHT
    Gosu::GpUp: KeyActions::UP
    Gosu::GpDown: KeyActions::DOWN

