source :rubygems
source "http://rubygems.org"

gem "hoe"
gem "rake-compiler"
gem "rdoc"
gem "rice"
gem "mocha"

gem "rspec-expectations", :git => "git://github.com/rspec/rspec-expectations.git"
gem "cucumber", :git => "git://github.com/cucumber/cucumber.git"
