sound_controller:
  effects:
    - filename: game-data/sounds/shoot_long.wav
      name: shoot
    - filename: game-data/sounds/footsteps.wav
      name: footsteps

  songs:
    - filename: game-data/music/splash.wav
      name: music
